/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoApp;

import controller.ProjectController;
import controller.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;
import util.ConnectionFactory;

public class App {
   

    public static void main(String[] args) {
       
        ProjectController projectController = new ProjectController();
        
        //Project project = new Project();
        //project.setName("Projeto Novo Nome");
        //project.setDescription("Descrição do projeto com nome alterado");
        //projectController.save(project);
        
        
        List<Project> projects = projectController.getAll();
        
        System.out.println("Total de projetos = " + projects.size());
        
        TaskController taskController = new TaskController();
        
        Task task = new Task();
        task.setIdProject(2);
        task.setName("Criar as telas da aplicação");
        task.setDescription("Devem ser criadas as telas para a aplicação");
        task.setNotes("Sem notas pae");
        task.setIsCompleted(false);
        task.setDeadline(new Date());
        
        taskController.save(task);
        
        
        
    }
}
